version: '3'

services:
  nginx:
    build:
      context: ./nginx
    image: brunobigotto/nginx-node
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: ./node
    image: brunobigotto/node-app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node index
    networks:
      - node-network
    volumes:
     - ./node:/usr/src/app
     - /usr/src/app/node_modules/
    tty: true
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    platform: linux/amd64
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
